/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class CreateOrderRequestBuilder {
    //the instance to build
    private CreateOrderRequest createOrderRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreateOrderRequestBuilder() {
        createOrderRequest = new CreateOrderRequest();
    }

    /**
     * Items
     */
    public CreateOrderRequestBuilder items(List<CreateOrderItemRequest> items) {
        createOrderRequest.setItems(items);
        return this;
    }

    /**
     * Customer
     */
    public CreateOrderRequestBuilder customer(CreateCustomerRequest customer) {
        createOrderRequest.setCustomer(customer);
        return this;
    }

    /**
     * Payment data
     */
    public CreateOrderRequestBuilder payment(CreatePaymentRequest payment) {
        createOrderRequest.setPayment(payment);
        return this;
    }

    /**
     * The order code
     */
    public CreateOrderRequestBuilder code(String code) {
        createOrderRequest.setCode(code);
        return this;
    }

    /**
     * The customer id
     */
    public CreateOrderRequestBuilder customerId(String customerId) {
        createOrderRequest.setCustomerId(customerId);
        return this;
    }

    /**
     * Shipping data
     */
    public CreateOrderRequestBuilder shipping(CreateShippingRequest shipping) {
        createOrderRequest.setShipping(shipping);
        return this;
    }

    /**
     * Metadata
     */
    public CreateOrderRequestBuilder metadata(LinkedHashMap<String, String> metadata) {
        createOrderRequest.setMetadata(metadata);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateOrderRequest build() {
        return createOrderRequest;
    }
}