/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class CreateUsageRequestBuilder {
    //the instance to build
    private CreateUsageRequest createUsageRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreateUsageRequestBuilder() {
        createUsageRequest = new CreateUsageRequest();
    }

    public CreateUsageRequestBuilder quantity(int quantity) {
        createUsageRequest.setQuantity(quantity);
        return this;
    }

    public CreateUsageRequestBuilder description(String description) {
        createUsageRequest.setDescription(description);
        return this;
    }

    public CreateUsageRequestBuilder usedAt(Date usedAt) {
        createUsageRequest.setUsedAt(usedAt);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateUsageRequest build() {
        return createUsageRequest;
    }
}