/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class GetBoletoTransactionResponseBuilder 
        extends GetTransactionResponseBuilder {
    //the instance to build
    private GetBoletoTransactionResponse getBoletoTransactionResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetBoletoTransactionResponseBuilder() {
        getBoletoTransactionResponse = new GetBoletoTransactionResponse();
    }

    public GetBoletoTransactionResponseBuilder url(String url) {
        getBoletoTransactionResponse.setUrl(url);
        return this;
    }

    public GetBoletoTransactionResponseBuilder barCode(String barCode) {
        getBoletoTransactionResponse.setBarCode(barCode);
        return this;
    }

    public GetBoletoTransactionResponseBuilder nossoNumero(String nossoNumero) {
        getBoletoTransactionResponse.setNossoNumero(nossoNumero);
        return this;
    }

    public GetBoletoTransactionResponseBuilder bank(String bank) {
        getBoletoTransactionResponse.setBank(bank);
        return this;
    }

    public GetBoletoTransactionResponseBuilder documentNumber(String documentNumber) {
        getBoletoTransactionResponse.setDocumentNumber(documentNumber);
        return this;
    }

    public GetBoletoTransactionResponseBuilder instructions(String instructions) {
        getBoletoTransactionResponse.setInstructions(instructions);
        return this;
    }

    public GetBoletoTransactionResponseBuilder billingAddress(GetBillingAddressResponse billingAddress) {
        getBoletoTransactionResponse.setBillingAddress(billingAddress);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetBoletoTransactionResponse build() {
        return getBoletoTransactionResponse;
    }
}