/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class GetCreditCardTransactionResponseBuilder 
        extends GetTransactionResponseBuilder {
    //the instance to build
    private GetCreditCardTransactionResponse getCreditCardTransactionResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetCreditCardTransactionResponseBuilder() {
        getCreditCardTransactionResponse = new GetCreditCardTransactionResponse();
    }

    public GetCreditCardTransactionResponseBuilder statementDescriptor(String statementDescriptor) {
        getCreditCardTransactionResponse.setStatementDescriptor(statementDescriptor);
        return this;
    }

    public GetCreditCardTransactionResponseBuilder acquirer(String acquirer) {
        getCreditCardTransactionResponse.setAcquirer(acquirer);
        return this;
    }

    public GetCreditCardTransactionResponseBuilder acquirerAffiliationCode(String acquirerAffiliationCode) {
        getCreditCardTransactionResponse.setAcquirerAffiliationCode(acquirerAffiliationCode);
        return this;
    }

    public GetCreditCardTransactionResponseBuilder acquirerTid(String acquirerTid) {
        getCreditCardTransactionResponse.setAcquirerTid(acquirerTid);
        return this;
    }

    public GetCreditCardTransactionResponseBuilder acquirerNsu(String acquirerNsu) {
        getCreditCardTransactionResponse.setAcquirerNsu(acquirerNsu);
        return this;
    }

    public GetCreditCardTransactionResponseBuilder acquirerAuthCode(String acquirerAuthCode) {
        getCreditCardTransactionResponse.setAcquirerAuthCode(acquirerAuthCode);
        return this;
    }

    public GetCreditCardTransactionResponseBuilder operationType(String operationType) {
        getCreditCardTransactionResponse.setOperationType(operationType);
        return this;
    }

    public GetCreditCardTransactionResponseBuilder creditCard(GetCreditCardResponse creditCard) {
        getCreditCardTransactionResponse.setCreditCard(creditCard);
        return this;
    }

    public GetCreditCardTransactionResponseBuilder installments(Integer installments) {
        getCreditCardTransactionResponse.setInstallments(installments);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetCreditCardTransactionResponse build() {
        return getCreditCardTransactionResponse;
    }
}