/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class GetOrderResponseBuilder {
    //the instance to build
    private GetOrderResponse getOrderResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetOrderResponseBuilder() {
        getOrderResponse = new GetOrderResponse();
    }

    public GetOrderResponseBuilder id(String id) {
        getOrderResponse.setId(id);
        return this;
    }

    public GetOrderResponseBuilder code(String code) {
        getOrderResponse.setCode(code);
        return this;
    }

    public GetOrderResponseBuilder currency(String currency) {
        getOrderResponse.setCurrency(currency);
        return this;
    }

    public GetOrderResponseBuilder items(List<GetOrderItemResponse> items) {
        getOrderResponse.setItems(items);
        return this;
    }

    public GetOrderResponseBuilder customer(GetCustomerResponse customer) {
        getOrderResponse.setCustomer(customer);
        return this;
    }

    public GetOrderResponseBuilder status(String status) {
        getOrderResponse.setStatus(status);
        return this;
    }

    public GetOrderResponseBuilder createdAt(Date createdAt) {
        getOrderResponse.setCreatedAt(createdAt);
        return this;
    }

    public GetOrderResponseBuilder updatedAt(Date updatedAt) {
        getOrderResponse.setUpdatedAt(updatedAt);
        return this;
    }

    public GetOrderResponseBuilder charge(GetChargeResponse charge) {
        getOrderResponse.setCharge(charge);
        return this;
    }

    public GetOrderResponseBuilder invoiceUrl(String invoiceUrl) {
        getOrderResponse.setInvoiceUrl(invoiceUrl);
        return this;
    }

    public GetOrderResponseBuilder shipping(GetShippingResponse shipping) {
        getOrderResponse.setShipping(shipping);
        return this;
    }

    public GetOrderResponseBuilder metadata(LinkedHashMap<String, String> metadata) {
        getOrderResponse.setMetadata(metadata);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetOrderResponse build() {
        return getOrderResponse;
    }
}