/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class GetPeriodResponseBuilder {
    //the instance to build
    private GetPeriodResponse getPeriodResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetPeriodResponseBuilder() {
        getPeriodResponse = new GetPeriodResponse();
    }

    public GetPeriodResponseBuilder startAt(Date startAt) {
        getPeriodResponse.setStartAt(startAt);
        return this;
    }

    public GetPeriodResponseBuilder endAt(Date endAt) {
        getPeriodResponse.setEndAt(endAt);
        return this;
    }

    public GetPeriodResponseBuilder id(String id) {
        getPeriodResponse.setId(id);
        return this;
    }

    public GetPeriodResponseBuilder billingAt(Date billingAt) {
        getPeriodResponse.setBillingAt(billingAt);
        return this;
    }

    public GetPeriodResponseBuilder subscription(GetSubscriptionResponse subscription) {
        getPeriodResponse.setSubscription(subscription);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetPeriodResponse build() {
        return getPeriodResponse;
    }
}