/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class UpdateSubscriptionPaymentMethodRequestBuilder {
    //the instance to build
    private UpdateSubscriptionPaymentMethodRequest updateSubscriptionPaymentMethodRequest;

    /**
     * Default constructor to initialize the instance
     */
    public UpdateSubscriptionPaymentMethodRequestBuilder() {
        updateSubscriptionPaymentMethodRequest = new UpdateSubscriptionPaymentMethodRequest();
    }

    /**
     * The new payment method
     */
    public UpdateSubscriptionPaymentMethodRequestBuilder paymentMethod(String paymentMethod) {
        updateSubscriptionPaymentMethodRequest.setPaymentMethod(paymentMethod);
        return this;
    }

    /**
     * Credit card's id
     */
    public UpdateSubscriptionPaymentMethodRequestBuilder creditCardId(String creditCardId) {
        updateSubscriptionPaymentMethodRequest.setCreditCardId(creditCardId);
        return this;
    }

    /**
     * Credit card's gateway id
     */
    public UpdateSubscriptionPaymentMethodRequestBuilder creditCardGatewayId(String creditCardGatewayId) {
        updateSubscriptionPaymentMethodRequest.setCreditCardGatewayId(creditCardGatewayId);
        return this;
    }

    /**
     * Credit card data
     */
    public UpdateSubscriptionPaymentMethodRequestBuilder creditCard(CreateCreditCardRequest creditCard) {
        updateSubscriptionPaymentMethodRequest.setCreditCard(creditCard);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public UpdateSubscriptionPaymentMethodRequest build() {
        return updateSubscriptionPaymentMethodRequest;
    }
}